# vim:ff=unix ts=2 sw=2 ai expandtab
---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-private-key
  - id: trailing-whitespace
- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.3
  hooks:
  - id: yamllint
    args:
    - -c
    - .github/yamllint.config.yaml
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.14
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
  - id: forbid-tabs
  - id: remove-tabs
